name: SuggestionBlocker64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.suggestionblocker64.SuggestionBlocker64
api-version: 1.17
depend: []
commands:
  blank:
    description: Main command for SuggestionBlocker64
permissions:
  suggestionblocker64.blank.base:
    description: Ability to use the /blank base-command
    default: op
  suggestionblocker64.blank.sub:
    description: Ability to use the /blank sub-command
    default: op