name: CmdFilter64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.cmdfilter64.CmdFilter64
api-version: 1.17
depend: []
commands:
  cmdfilter:
    description: Main command for CmdFilter64
permissions:
  cmdfilter64.admin:
    description: Ability to use the /cmdfilter admin command
    default: op
  cmdfilter64.bypass:
    description: Ability to bypass the suggestion blacklist
    default: op