name: SuggestionBlocker64
version: ${project.version}
description: ${project.description}
author: tbm00
main: dev.tbm00.spigot.suggestionblocker64.SuggestionBlocker64
api-version: 1.17
depend: []
commands:
  sugblock:
    description: Main command for SuggestionBlocker64
permissions:
  suggestionblocker64.admin:
    description: Ability to use the /sugblock command
    default: op
  suggestionblocker64.bypass:
    description: Ability to bypass the suggestion filter
    default: op